tanzawa/core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.utils import text
from plugins import pool

from . import views

urlpatterns = [
    path("a/", include("entry.urls")),
    path("a/", include("post.urls", namespace="post")),
    path("a/", include("files.admin_urls")),
    path("a/", include("trips.urls")),
    path("a/", include("plugins.urls")),
    path("a/wordpress/", include("wordpress.urls", namespace="wordpress")),
    path("a/", include("indieweb.urls", namespace="indieweb")),
    path("files/", include("files.urls")),
    path("", include("feeds.urls", namespace="feeds")),
    path("webmention/", include("webmention.urls")),
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
]

# Include any plugin urls after core urls.
plugin_urls = [path("", include(plugin_urls)) for plugin_urls in pool.plugin_pool.urls()]
urlpatterns.extend(plugin_urls)

plugin_admin_urls = [
    path(f"a/plugins/{text.slugify(plugin.name)}/", include(plugin.admin_urls))
    for plugin in pool.plugin_pool.enabled_plugins()
    if plugin.admin_urls
]
urlpatterns.extend(plugin_admin_urls)

# Public urls are last so "slug-like" urls in plugins are not matched to the stream-list view.
urlpatterns.append(
    path("", include("public.urls", namespace="public")),
)


handler404 = views.handle404

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

tanzawa/plugins/urls.py
from django.urls import path, re_path

from . import views

app_name = "plugins"

urlpatterns = [
    path("plugins/", views.plugin_list, name="plugin_list"),
    re_path(r"^plugins/(?P<identifier>[a-z.]+)/enable/$", views.enable_plugin, name="plugin_enable"),
    re_path(r"^plugins/(?P<identifier>[a-z.]+)/disable/$", views.disable_plugin, name="plugin_disable"),
]

tanzawa/plugins/tanzawa_plugin/now/forms.py
from django import forms as django_forms
from trix import forms as trix_forms


class UpdateNow(django_forms.Form):
    content = trix_forms.TrixField(required=False, label="What are you focusing on now?")

tanzawa/plugins/views.py
from django.contrib import messages
from django.contrib.auth import decorators as auth_decorators
from django.shortcuts import redirect, render
from django.views.decorators import http
from plugins import pool
from plugins.application import activation


@auth_decorators.login_required
def plugin_list(request):

    return render(
        request,
        "plugins/plugin_list.html",
        {"available_plugins": pool.plugin_pool.get_all_plugins(), "nav": "plugins", "page_title": "Plugins"},
    )


@auth_decorators.login_required
@http.require_POST
def enable_plugin(request, identifier: str):
    plugin = pool.plugin_pool.get_plugin(identifier)
    if not plugin:
        messages.error(request, "Plugin not found.")
        return redirect("plugins:plugin_list")
    pool.plugin_pool.enable(plugin)
    messages.success(request, f"{plugin.name} enabled.")
    activation.restart_parent_process()
    return redirect("plugins:plugin_list")


@auth_decorators.login_required
@http.require_POST
def disable_plugin(request, identifier: str):
    plugin = pool.plugin_pool.get_plugin(identifier)
    if not plugin:
        messages.error(request, "Plugin not found.")
        return redirect("plugins:plugin_list")
    pool.plugin_pool.disable(plugin)
    messages.success(request, f"{plugin.name} disabled.")
    activation.restart_parent_process()
    return redirect("plugins:plugin_list")

tanzawa/templates/plugins/fragments/plugin_list.html
{% extends "fragments/content.html" %}

{% block breadcrumbs %}
    <a href="{% url "plugins:plugin_list" %}" class="underline">Plugins</a>
{% endblock %}

{% block main %}
    <p>Selectively enable or disable functionality on your Tanzawa website.<br/>
        Learn how to make your own plugins in the <a href="https://jamesvandyne.github.io/tanzawa/" class="underline">developer documentation</a>.
    </p>
    <h1 class="mt-2 text-xl">Available Plugins</h1>
    <ul class="mt-2">
    {% for plugin in available_plugins %}
        <li class="flex {% if not forloop.last %}border-bottom{% endif %}">
            <div class="flex flex-col mr-2 w-96">
                <h2 class="">{{ plugin.name }}</h2>
                <p class="mt-2 text-sm">{{ plugin.description }}</p>
            </div>
            <div class="flex flex-col">
            {% if plugin.is_enabled and plugin.settings_url %}
                <a href="{{ plugin.settings_url }}" class="mt-2 outline-button text-sm">Settings</a>
            {% endif %}
            <div class="flex flex-col flex-grow justify-end">
            {% if plugin.is_enabled %}
                <form  method="post" action="{% url 'plugins:plugin_disable' plugin.identifier %}" class="{% if plugin.settings_url %} justify-end{% endif %}">
                    {% csrf_token %}
                    <button type="submit" class="px-3 py-1 text-negroni-800 text-xs mr-2" href="">Disable</button>
                </form>
            {% else %}
                <form  method="post" action="{% url 'plugins:plugin_enable' plugin.identifier %}">
                    {% csrf_token %}
                    <button type="submit" class="px-3 py-1 text-negroni-800 text-xs mr-2" href="">Enable</button>
                </form>
            {% endif %}
            </div>
            </div>
        </li>
    {% endfor %}
    </ul>
{% endblock %}